name: Release

on: [ workflow_dispatch ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Prepare
      run: |
        sudo apt-get update -y
        sudo apt install qjackctl pulseaudio-module-jack libjack-jackd2-dev
    - name: cargo plugin cache
      id: cargo-plugin-cache
      uses: actions/cache@v2
      with:
        path: ~/.cargo/bin/
        key: ${{ runner.os }}-cargo-plugins
    - name: install cargo plugin
      if: steps.cargo-plugin-cache.outputs.cache-hit != 'true'
      run: cargo install cargo-release
    - name: Release
      run: |
        git config --global user.email "ruimo.uno@gmail.com"
        git config --global user.name "Shisei Hanai"
        cargo login ${{ secrets.KLAVIER_JACK }}
        git status
        cargo release release -vv --execute --no-confirm
